### ISSUE TITLE
URI with encoded characters not supported

### ISSUE THREAD

**Issue by andreibosco** [avency/coap-cli#11]
Hello. I know you are busy and not able to actively maintain coap-cli, but I'm reporting this in case someone else hits this bug or take the lead of the project.

When I enter a URI with an encoded character, e.g. coap://example.com:5683/ps/%2F/cached, coap-cli does not decode the character and sends %2F in the URI-Path. RFC 7252, Appendix B suggests that / (the decoded character) should be sent instead.

I'm using coap-cli 0.4.0.

**Comment by mcollina** [comment]
You migt want to send a PR ;).
Il giorno gio 3 mar 2016 alle 12:52 Andrei Bosco <notifications@github.com>
ha scritto:
