### ISSUE TITLE
CLI does not exit since 0.11.0

### ISSUE THREAD

**Issue by JcBernack** [avency/coap-cli#136]
Since the update to version 0.11.0 the CLI application does not exit anymore. The request is handled as expected but the program does not exit afterwards until forced with ctrl-c. Until 0.10.1 the application is exiting normally after the request is handled.

I didn't have time to debug it yet, but I'm guessing it has to do with upstream changes from `node-coap@1.0`.

**Comment by JKRhb** [comment]
Thank you for reporting this issue, @JcBernack, I actually already found the bug in the meantime (the globally defined UDP agents seem to somehow prevent the application from being closed) and try to come up with a fix as soon as possible.

**Comment by JKRhb** [comment]
I actually managed to find the bug: The observe option seems to be set to `false`, which is not handled correctly by node-coap. I will open a PR for that soon :)

**Comment by JcBernack** [comment]
That was quick, thanks! :laughing:

**Comment by JKRhb** [comment]
> That was quick, thanks! 😆

You're welcome :) The PR has been merged by now, updating the dependencies here should now resolve the issue :)
