### ISSUE TITLE
Support DTLS Setup

### ISSUE THREAD

**Issue by jcrbsa** [avency/coap-cli#37]
Not is possible include digital certified  file to realizade DTLS connection in CoAP messages

To development DTLS setup logic in client-side and to create new parameter to identify  the operation when digital certified file is used. 

For instance, it's necessary to investigate change points your source-code .

No additional context
#

**Comment by gerdemann** [comment]
Thank you for your message, jcrbsa.

Unfortunately node-coap does not support DTLS yet, so it cannot be implemented in this client.
There is an open issue in node-coap:
https://github.com/mcollina/node-coap/issues/11

I close the issue until the support is available in node-coap.
