### ISSUE TITLE
Add CoAP Option in Request

### ISSUE THREAD

**Issue by jcrbsa** [avency/coap-cli#40]
What is the way to make request with coAp option? #17 

Itried this way, but it didn't work:

### **1)"-O" option command:**
**Input;**

`coap get -O "test" + , + "test" coap://localhost:5684/basic`

**Output:**

Error: Option 'test' is invalid.
Please provide options in this way:
-O [Key]" + coapOptionSeperator + "[Value]
OR --coap-option [Key],[Value]

### **2)"--coap-option" option command:**

**Input:**

`coap get --coap-option [test],[test] coap://localhost:5684/basic`

**Output:**

Error: Option '[test],[test]' is invalid.
Please provide options in this way:
-O [Key]" + coapOptionSeperator + "[Value]
OR --coap-option [Key],[Value]

Could you provide some sample?

**Comment by BlueBeN82** [comment]
Hi @jcrbsa!

I've just added an enhanced documentation. There are two problems with the way you are trying it.
1. Wrong syntax, should be `coap get -O 2048,HelloWorld`
2. Your using a string as key, but coap only allows numeric keys like 2048

Hope that helps.

BR
Bernd
