### ISSUE TITLE
Tokens with 8 bit length

### ISSUE THREAD

**Issue by gonzobrandon** [avency/coap-cli#5]
Why does this and [other coap modules](https://github.com/mcollina/node-coap). not accept 8 bit tokens? Its a valid token length according to the [IETF spec.](https://tools.ietf.org/html/draft-ietf-core-coap-18#section-5.3.1). This is a fine module, but not workable with 8 bit servers. 
Always getting:

```
throw new RangeError('Trying to access beyond buffer length');
```

**Comment by mcollina** [comment]
It is me being lazy. I think that node-coap was fixed with 8bit tokens. Maybe this one was not updated though.

Would you like to help and send a PR to address this issue?

**Comment by gerdemann** [comment]
That was a problem in node-coap and not one in coap-cli, right?

**Comment by gerdemann** [comment]
No update for a long time, so I close the Issue.
